#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰼏  󰼐  󰼑  󰼒  󰼓  󰼔 

bspc config border_radius       50
bspc config border_width         4
bspc config window_gap          10

bspc config focused_border_color "#baffc9"
bspc config normal_border_color "#fea1ff"
bspc config active_border_color "#ffffba"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar &
xrandr -s 1920x1080
nitrogen --restore
$HOME/.config/polybar/launch.sh
picom
